version: '3'
services:
  configuration:
    image: gozdzseb/configuration
    container_name: configuration
    environment:
      - SERVER_PORT=80
  discovery:
    image: gozdzseb/discovery
    container_name: discovery
    depends_on:
      - configuration
    environment:
      - ACTIVE_PROFILE=development
      - CONFIGURATION_SERVER_URI=http://configuration
  gateway:
    image: gozdzseb/gateway
    container_name: gateway
    depends_on:
      - configuration
      - discovery
    environment:
      - SERVER_PORT=80
      - ACTIVE_PROFILE=development
      - CONFIGURATION_SERVER_URI=http://configuration
    ports:
      - 80:80
  orders:
    image: gozdzseb/orders
    container_name: orders
    depends_on:
      - configuration
      - discovery
    environment:
      - ACTIVE_PROFILE=development
      - CONFIGURATION_SERVER_URI=http://configuration
  payments:
    image: gozdzseb/payments
    container_name: payments
    depends_on:
      - configuration
      - discovery
    environment:
      - ACTIVE_PROFILE=development
      - CONFIGURATION_SERVER_URI=http://configuration